object Libs {
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx"
    const val ANDROIDX_HILT_COMPILER = "androidx.hilt:hilt-compiler"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val SWIPE_REFRESH = "androidx.swiperefreshlayout:swiperefreshlayout"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
    const val MATERIAL = "com.google.android.material:material"
    const val RECYCLER_VIEW = "androidx.recyclerview:recyclerview"
    const val FRAGMENT = "androidx.fragment:fragment-ktx"
    const val VIEW_PAGER_2 = "androidx.viewpager2:viewpager2"
    const val NAVIGATION_UI = "androidx.navigation:navigation-ui-ktx"
    const val NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment-ktx"
    const val TIMBER = "com.jakewharton.timber:timber"
    const val PAGING = "androidx.paging:paging-runtime-ktx"
    const val OK_HTTP = "com.squareup.okhttp3:okhttp"
    const val OK_HTTP_LOGGING = "com.squareup.okhttp3:logging-interceptor"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_GSON = "com.squareup.retrofit2:converter-gson"
    const val GLIDE = "com.github.bumptech.glide:glide"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler"
    const val GLIDE_TRANSFORMATIONS = "jp.wasabeef:glide-transformations"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib-jdk7"
    const val ROOM_KTX = "androidx.room:room-ktx"
    const val ROOM_RUNTIME = "androidx.room:room-runtime"
    const val ROOM_COMPILER = "androidx.room:room-compiler"
    const val GSON = "com.google.code.gson:gson"



    const val JUNIT = "junit:junit"
    const val ANDROID_JUNIT = "androidx.test.ext:junit"
    const val ESPRESSO = "androidx.test.espresso:espresso-core"
}